const crypto = require('crypto');
const allowedTypes = new Set(['settings','news','events','results','documents','people','gallery','clubs','partners','social','pages']);
function json(statusCode, body, headers={}){return {statusCode,headers:{'content-type':'application/json; charset=utf-8',...headers},body:JSON.stringify(body)}}
function env(name){const v=process.env[name]; if(!v) throw new Error(`Missing env ${name}`); return v;}
function parseCookies(header=''){return Object.fromEntries(header.split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return [decodeURIComponent(v.slice(0,i)),decodeURIComponent(v.slice(i+1))]}));}
function sign(value){return crypto.createHmac('sha256', env('SESSION_SECRET')).update(value).digest('hex');}
function makeSession(){const value=`admin:${Date.now()}`; return `${value}.${sign(value)}`;}
function verifySession(event){const token=parseCookies(event.headers.cookie||event.headers.Cookie||'').fgsm_session; if(!token) return false; const i=token.lastIndexOf('.'); if(i<0)return false; const value=token.slice(0,i), sig=token.slice(i+1); try{return crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(sign(value)));}catch{return false;}}
function cookieHeader(token){return `fgsm_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=604800`;}
function clearCookie(){return `fgsm_session=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0`;}
function ghHeaders(){return {'Authorization':`Bearer ${env('GITHUB_TOKEN')}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'fgsm-dual-admin'};}
function contentPath(type){if(!allowedTypes.has(type)) throw new Error('Invalid content type'); return `content/${type}.json`;}
async function ghGetFile(type){const owner=env('GITHUB_OWNER'), repo=env('GITHUB_REPO'), branch=process.env.GITHUB_BRANCH||'main'; const path=contentPath(type); const url=`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}?ref=${encodeURIComponent(branch)}`; const res=await fetch(url,{headers:ghHeaders()}); if(res.status===404) return {sha:null,data:type==='settings'?{}:{items:[]}}; if(!res.ok) throw new Error(`GitHub read failed ${res.status}: ${await res.text()}`); const meta=await res.json(); const text=Buffer.from(meta.content||'', 'base64').toString('utf8'); return {sha:meta.sha,data:text?JSON.parse(text):(type==='settings'?{}:{items:[]})};}
async function ghPutFile(type,data,message){const owner=env('GITHUB_OWNER'), repo=env('GITHUB_REPO'), branch=process.env.GITHUB_BRANCH||'main'; const path=contentPath(type); const current=await ghGetFile(type); const body={message:message||`Update ${path}`,content:Buffer.from(JSON.stringify(data,null,2)+'\n').toString('base64'),branch}; if(current.sha) body.sha=current.sha; const url=`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}`; const res=await fetch(url,{method:'PUT',headers:{...ghHeaders(),'content-type':'application/json'},body:JSON.stringify(body)}); if(!res.ok) throw new Error(`GitHub write failed ${res.status}: ${await res.text()}`); return res.json();}
function ensureItemPayload(data,type){ if(type==='settings') return data; if(!data || !Array.isArray(data.items)) return {items:[]}; return data; }
module.exports={json,env,makeSession,verifySession,cookieHeader,clearCookie,allowedTypes,ghGetFile,ghPutFile,ensureItemPayload};
